name: youhealmobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+2

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.1
  font_awesome_flutter: ^10.4.0
  provider: ^6.0.5
  shared_preferences: ^2.0.18
  http: ^0.13.5
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.0.4
  animations: ^2.0.7
  flutter_launcher_icons: ^0.12.0
  cached_network_image: ^3.2.3
  intl_phone_field: ^3.1.0
  youtube_player_flutter: ^8.1.2
  image_picker: ^0.8.9
  video_player: ^2.6.1
  mime: ^1.0.4
  change_app_package_name: ^1.1.0
  firebase_core: ^2.14.0
  flutter_local_notifications: ^14.1.1
  firebase_messaging: ^14.6.3
  pdf: ^3.10.4
  path_provider: ^2.0.15
  url_launcher: ^6.1.11
  open_file: ^3.3.2
  permission_handler: ^10.3.0
  otp_text_field: ^1.1.3
  flutter_sound: ^9.2.13
  audioplayers: ^4.1.0
  dio: ^5.2.1+1
  material_design_icons_flutter: ^7.0.7296
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21


flutter:
  uses-material-design: true


  assets:
    - assets/langs/
    - assets/images/

  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
    - family: Poppins-SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: Raleway-Bold
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
    - family: Alexandria
      fonts:
        - asset: assets/fonts/Alexandria-Regular.ttf
    - family: NotoSansArabic
      fonts:
        - asset: assets/fonts/NotoSansArabic-Regular.ttf
    - family: NotoNaskhArabic
      fonts:
        - asset: assets/fonts/NotoNaskhArabic-Regular.ttf
    
  
